/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './app/routes/__root'
import { Route as IndexImport } from './app/routes/index'
import { Route as DataSheetsIndexImport } from './app/routes/data-sheets/index'

// Create/Update Routes

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const DataSheetsIndexRoute = DataSheetsIndexImport.update({
  id: '/data-sheets/',
  path: '/data-sheets/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/data-sheets/': {
      id: '/data-sheets/'
      path: '/data-sheets'
      fullPath: '/data-sheets'
      preLoaderRoute: typeof DataSheetsIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/data-sheets': typeof DataSheetsIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/data-sheets': typeof DataSheetsIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/data-sheets/': typeof DataSheetsIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/data-sheets'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/data-sheets'
  id: '__root__' | '/' | '/data-sheets/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DataSheetsIndexRoute: typeof DataSheetsIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DataSheetsIndexRoute: DataSheetsIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/data-sheets/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/data-sheets/": {
      "filePath": "data-sheets/index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
